apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  key1: value1
  key2: value2
  key3: value3
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-config
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen {{ .Values.deployment.containerPort }};
        location / {
          root /homework;
          index index.html;
        }
      }
    }
