# Необходимо 
# - Изменить манифест deployment из прошлых Д3 так, чтобы поды запускались под service account monitoring


apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Release.Name }}-monitoring
      nodeSelector:
        homework: "true" 
      containers:
      - name: {{ .Release.Name }}-web-server
        image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag | default .Chart.AppVersion }}"
        ports:
        - containerPort: {{ .Values.deployment.containerPort }}
        volumeMounts:
        - name: shared-data
          mountPath: /homework
        - name: config-volume
          mountPath: /homework/conf
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "rm /homework/index.html"] # удалять файл index.html из директории /homework основного контейнера, перед его завершением
        {{- if .Values.deployment.readinessProbeEnable }}
        readinessProbe:
          httpGet:
            path: /index.html
            port: {{ .Values.deployment.containerPort }}
          initialDelaySeconds: 5
          periodSeconds: 10
        {{- end }}
      initContainers:
      - name: {{ .Release.Name }}-init-container
        image: "{{ .Values.deployment.imageInit.repository }}:{{ .Values.deployment.imageInit.tag | default .Chart.AppVersion }}" 
        volumeMounts:
        - name: shared-data
          mountPath: /init
        command: ['sh', '-c', 'echo "<html><head><title>Welcome</title></head><body><h1>Hello, world!</h1></body></html>" > /init/index.html']
        # command:
        # - wget
        # - "-O"
        # - "/init/index.html"
        # - http://info.cern.ch
      volumes:
      - name: shared-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-pvc
      - name: config-volume
        configMap:
          name: {{ .Release.Name }}-configmap
      - name: nginx-config-volume
        configMap:
          name: {{ .Release.Name }}-nginx-config
