apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-monitoring-metrics-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-metrics-reader
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-monitoring
  namespace: {{ .Release.Namespace }}