# Создать манифест deployment для оператора, указав созданный ранее ServiceAccount и образ roflmaoinmysoul/mysql-operator:1.0.0
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-operator
  namespace: hwmysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-operator
  template:
    metadata:
      labels:
        app: mysql-operator
    spec:
      serviceAccountName: mysql-operator-sa
      containers:
        - name: mysql-operator
          image: roflmaoinmysoul/mysql-operator:1.0.0
          ports:
            - containerPort: 8080