apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring
  namespace: homework
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cd
  namespace: homework
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: cd
  annotations:
    kubernetes.io/service-account.name: "cd"